version: '3.8'

services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose Django on port 8000
    volumes:
      - .:/eLearningApp
    environment:
      - DJANGO_SETTINGS_MODULE=eLearningApp.settings
    restart: always
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/eLearningApp
    environment:
      - DJANGO_SETTINGS_MODULE=eLearningApp.settings
    restart: always
    depends_on:
      - redis
    command: celery -A eLearningApp worker -l INFO

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/localhost.crt:/etc/nginx/certs/fullchain.pem
      - ./certs/localhost.key:/etc/nginx/certs/privkey.pem
    restart: always

  # daphne:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile  # You might have a separate Dockerfile for Daphne
  #   command: daphne -b localhost -p 8001 eLearningApp.asgi:application  # Adjust as needed
  #   depends_on:
  #     - django
  #   ports:
  #     - "8001:8001"  # Expose Daphne port
  #   restart: always
  #   networks:
  #     - mynetwork

