services:
  # A Docker web service
  - type: web
    name: django
    runtime: docker
    region: singapore 
    plan: free 
    branch: main 
    rootDir: eLearningApp
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis
          property: port

  # Celery instance
  - type: worker
    name: celery
    runtime: python3
    startCommand: celery -A eLearningApp worker -l INFO
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eLearningApp.settings
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis
          property: port
      - key: CELERY_BROKER_URL
        value: redis://redis:6379/0

  # Nginx service
  - type: web
    name: nginx
    runtime: image
    image:
      url: docker.io/library/nginx:latest # Or any other version/tag you prefer
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eLearningApp.settings
    disk:
      name: nginx-data
      mountPath: /etc/nginx
