services:
  - type: web
    name: django
    dockerfile: Dockerfile
    context: .
    branchFilters:
      - main  # Adjust to your main branch name

  - type: redis
    name: redis
    image: redis:latest

  - type: worker
    name: celery
    dockerfile: Dockerfile
    context: .
    branchFilters:
      - main  # Adjust to your main branch name

  - type: web
    name: nginx
    image: nginx:latest
    branchFilters:
      - main  # Adjust to your main branch name
