services:
  - type: web
    name: django
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eLearningApp.settings
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: "6379"
    startCommand: "daphne -b 0.0.0.0 -p 8000 eLearningApp.asgi:application"
    healthCheckPath: "/health-check" # You can adjust this accordingly
    buildCommand: "docker build -t your_django_image -f Dockerfile ."
    automaticDeployment:
      branchFilters:
        - main  # Adjust to your main branch name

  - type: redis
    name: redis
    startCommand: "redis-server"
    healthCheckPath: "/" # You can adjust this accordingly

  - type: worker
    name: celery
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eLearningApp.settings
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: "6379"
      - key: CELERY_BROKER_URL
        value: "redis://redis:6379/0"
    startCommand: "celery -A eLearningApp worker -l INFO"
    healthCheckPath: "/" # You can adjust this accordingly
    buildCommand: "docker build -t your_celery_image -f Dockerfile ."
    automaticDeployment:
      branchFilters:
        - main  # Adjust to your main branch name

  - type: web
    name: nginx
    startCommand: "nginx -g 'daemon off;'"
    healthCheckPath: "/" # You can adjust this accordingly
    automaticDeployment:
      branchFilters:
        - main  # Adjust to your main branch name
