# Generated by Django 5.0 on 2024-02-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
    ]
