# Generated by Django 5.0 on 2024-02-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0002_course_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'teacher')},
        ),
    ]
