# Generated by Django 5.0 on 2024-02-13 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0002_course_created_at_course_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
