# Generated by Django 5.0 on 2024-02-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0003_remove_enrollment_start_date_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
