# Generated by Django 5.0 on 2024-02-13 13:54

import eLearning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0005_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='/photos/default_profile_picture.png', null=True, upload_to=eLearning.models.profile_picture_upload_path),
        ),
    ]
