# Generated by Django 5.0 on 2024-02-15 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(verbose_name='Comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='course_rating',
            field=models.IntegerField(verbose_name='Course Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='teacher_rating',
            field=models.IntegerField(verbose_name='Teacher Rating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
