# Generated by Django 5.0 on 2024-02-15 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0007_remove_feedback_content_enrollment_is_banned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (weeks)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Course Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Teacher Rating'),
        ),
    ]
