# Generated by Django 5.0 on 2024-03-06 11:26

import chat.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_online_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when the user disconnects')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(help_text='The name of the chat room.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='The text content of the message.', max_length=2048, null=True)),
                ('file', models.FileField(blank=True, help_text='Optional file attachment.', null=True, upload_to=chat.models.message_file_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the message was created.')),
            ],
        ),
    ]
