# Generated by Django 5.0 on 2024-02-16 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
