# Generated by Django 5.0 on 2024-02-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_content'),
        ('eLearning', '0009_remove_assignment_is_submitted_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='course',
            field=models.OneToOneField(help_text='The course associated with this chat room.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='eLearning.course'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(help_text='The name of the chat room.', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('course', 'name')},
        ),
    ]
