# Generated by Django 5.0 on 2024-02-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='chat_name',
        ),
    ]
