# Generated by Django 5.0 on 2024-03-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmembership',
            old_name='last_online_timestamp',
            new_name='last_active_timestamp',
        ),
    ]
