# Generated by Django 5.0 on 2024-02-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_unique_together_and_more'),
        ('eLearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_name',
            field=models.CharField(default='', help_text='The name of the chat room.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('course', 'chat_name')},
        ),
    ]
