# Generated by Django 5.0 on 2024-02-26 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmembership_last_online_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembership',
            name='last_online_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when the user disconnects'),
        ),
    ]
